# -*- coding: utf-8 -*-
"""gráficos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10MpefXf5vNDMyKs6NQ_1RgSalmooPItS
"""

import matplotlib.pyplot as plt
import numpy as np
import math

# Sendo  N = 5

#Busca Binária
qbb = np.array(['10^4','10^5' , '10^6', '10^7'])
tbb = np.array([0.2655, 0.3217, 0.4844, 1.4739])

plt.plot(qbb, tbb,  label='Busca Binária')

#Busca Otimizada

qbo = np.array(['10^4','10^5' , '10^6', '10^7'])
tbo = np.array([157.10, 972.15, 1001.71, 936.83])

plt.plot(qbo, tbo,  label= 'Busca Otimizada')

#Busca Sequencial

qbs = np.array(['10^4','10^5' , '10^6', '10^7'])
tbs = np.array([ 120.15, 946.71, 7286.0, 65449.36])

plt.plot( qbs, tbs, label = 'Busca Sequencial')

plt.title('Número de Buscas(q) = 10^5')
plt.ylabel('Tempo(segundos)', fontsize = 12)
plt.xlabel('Tamanho da Sequência(n)', fontsize = 12)
plt.legend()


plt.show()

# Sendo N = 4

#Busca Binária
qbb = np.array(['10^4','10^5' , '10^6', '10^7'])
tbb = np.array([0.015, 0.32, 0.109, 1.06])

plt.plot(qbb, tbb, label='Busca Binária')

#Busca Otimizada

qbo = np.array(['10^4','10^5' , '10^6', '10^7'])
tbo = np.array([9.22, 9.04, 9.20, 11.12])

plt.plot(qbo, tbo, label='Busca Otimizada')

#Busca Sequencial

qbs = np.array(['10^4','10^5' , '10^6', '10^7'])
tbs = np.array([6.46, 70.75, 649.78, 6813.85])

plt.plot(qbs, tbs, label='Busca Sequencial')

plt.title('Número de Buscas(q) = 10^4')
plt.ylabel('Tempo(segundos)', fontsize = 12)
plt.xlabel('Tamanho da Sequência(n)', fontsize = 12)
plt.legend()

plt.show()

# Sendo N = 3

#Busca Binária
qbb = np.array(['10^4','10^5' , '10^6', '10^7'])
tbb = np.array([0.0001, 0.015, 0.077, 1.022])

plt.plot(qbb, tbb, label='Busca Binária')

#Busca Otimizada

qbo = np.array(['10^4','10^5' , '10^6', '10^7'])
tbo = np.array([0.781, 0.0624, 0.172, 1.012])

plt.plot(qbo, tbo, label='Busca Otimizada')

#Busca Sequencial

qbs = np.array(['10^4','10^5' , '10^6', '10^7'])
tbs = np.array([0.75, 7, 68.27, 648.29])

plt.plot(qbs, tbs, label='Busca Sequencial')


plt.title('Número de Buscas(q) = 10^3')
plt.ylabel('Tempo(segundos)', fontsize = 12)
plt.xlabel('Tamanho da Sequência(n)', fontsize = 12)
plt.legend()

plt.show()

# Sendo Q = 2


#Busca Binária
qbb = np.array(['10^4','10^5' , '10^6', '10^7'])
tbb = np.array([0, 0.016, 0.063, 1.161])

plt.plot(qbb, tbb, label='Busca Binária')

#Busca Otimizada

qbo = np.array(['10^4','10^5' , '10^6', '10^7'])
tbo = np.array([0, 0, 0, 0])

plt.plot(qbo, tbo, label='Busca Otimizada')

#Busca Sequencial

qbs = np.array(['10^4','10^5' , '10^6', '10^7'])
tbs = np.array([0.056, 0.79, 6.53, 73.01])

plt.plot(qbs, tbs, label='Busca Sequencial')

plt.title('Número de Buscas(q) = 10^2')
plt.ylabel('Tempo(segundos)', fontsize = 12)
plt.xlabel('Tamanho da Sequência', fontsize = 12)
plt.legend()

plt.show()